print("================================")
print("Nama\t: Mohammad Adam Nur")
print("NIM\t: 19230359")
print("Kelas\t: 19.1A.39")
print("Jurusan\t: Sistem Informasi")
print("================================")
