print("===================================")
nim = int(input("NIM: "))
nama = str(input("Nama Lengkap: "))
jurusan = str(input("Jurusan: "))
alamat = str(input("Alamat Lengkap: "))
print("===================================")

print("\n")

print("===================================")
print("NIM\t: {}".format(nim))
print("Nama\t: {}".format(nama))
print("Jurusan\t: {}".format(jurusan))
print("Alamat\t: {}".format(alamat))
print("===================================")

print("===================================")
print("Data Diri Mahasiswa")
print("--------------------")
print("Nim anda {} dengan nama {}".format(nim, nama))
print("Anda berada di Jurusan {} dan anda tinggal di {}".format(jurusan, alamat))
print("===================================")